export const TRASH_TABS = [
  'Users',
  'Workers',
  'Bookings',
  'Reviews',
  'Industries',
  'Skills',
  'Conversations',
  'Notifications',
  'Reports',
];

export {
  loadTrash,
  permanentlyDeleteTrash,
  restoreTrash,
  restoreAccountFromTrash,
  restoreBookingFromTrash,
  restorePaymentFromTrash,
  restoreIndustryFromTrash,
  restoreSkillFromTrash,
  restoreConversationFromTrash,
  restoreNotificationCampaignFromTrash,
  hardDeleteAccountFromTrash,
  hardDeleteBookingFromTrash,
  hardDeletePaymentFromTrash,
  hardDeleteIndustryFromTrash,
  hardDeleteSkillFromTrash,
  hardDeleteConversationFromTrash,
  hardDeleteNotificationCampaignFromTrash,
  restoreReportExportFromTrash,
  hardDeleteReportExportFromTrash,
  restoreBookingProofFromTrash,
  hardDeleteBookingProofFromTrash,
} from '../../../services/trash';
