import { useLoginController } from '../hooks/useLoginController';

export function useLoginPageController() {
  const {
    email,
    error,
    handleSubmit,
    isLoading,
    isRecovery,
    newPassword,
    setNewPassword,
    confirmPassword,
    setConfirmPassword,
    showNewPassword,
    setShowNewPassword,
    resetComplete,
    signupComplete,
    password,
    setEmail,
    setPassword,
    setShowPassword,
    showPassword,
    systemStatus,
  } = useLoginController();
  return {
    email,
    error,
    handleSubmit,
    isLoading,
    isRecovery,
    newPassword,
    setNewPassword,
    confirmPassword,
    setConfirmPassword,
    showNewPassword,
    setShowNewPassword,
    resetComplete,
    signupComplete,
    password,
    setEmail,
    setPassword,
    setShowPassword,
    showPassword,
    systemStatus,
  };
}
